name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.python_version }}
  - python-dotenv>=0.10
  - black
  - flake8
  - pytest
  - pip
  - pip:
    - -e ./src{% if cookiecutter.dvc_remote_type == 'Amazon S3' %}
  - dvc[s3]{% elif cookiecutter.dvc_remote_type == 'Google Cloud Storage' %}
  - dvc[gs]{% elif cookiecutter.dvc_remote_type == 'Azure' %}
  - dvc[azure]{% elif cookiecutter.dvc_remote_type == 'SSH' %}
  - dvc[ssh]{% elif cookiecutter.dvc_remote_type == 'All' %}
  - dvc{% endif %}
